### ISSUE TITLE
RuntimeError: Wrong PC ??? when using a speed limited CPU

### ISSUE THREAD

**Issue by Qu1ruX** [6809/MC6809#4]
Hi, I am not sure this qualifies as an issue. I would generally put this in a discussion tab but there does not seem to be one for this repository. Anyway, I am trying to execute the following code on an instance of the class **CPUSpeedLimit**:
```python
self.cpu.memory.load(0x100, bytearray([
    # A = atoi(*(0x1000)) + atoi(*(0x1001)):
    0xB6, 0x10, 0x00,   # LDA       (extended)      0x1000
    0x80, 0x30,         # SUBA      (immediate)     0x30 (48 in base 10)
    0xF6, 0x10, 0x01,   # LDB       (extended)      0x1001
    0xC0, 0x30,         # SUBB      (immediate)     0x30 (48 in base 10)
    0xF7, 0x10, 0x02,   # STB       (extended)      0x1002
    0xBB, 0x10, 0x02    # ADDA      (extended)      0x1002
]))

self.cpu.program_counter.set(0x100)

self.cpu.run(target_cycles_per_sec=1)
```
But upon running it, I get the following error:
`
File "MC6809/MC6809/components/mc6809_base.py", line 787, in instruction_NEG_memory
    raise RuntimeError("Wrong PC ???")
RuntimeError: Wrong PC ???
`
I am not sure about what causes this error. Again, I apologize if it is the wrong place to ask but I did not really know where to put my message. Thanks in advance.

**Comment by jedie** [comment]
I open discussions: https://github.com/6809/MC6809/discussions ;)

Off the top of my head, I have no idea where the problem lies.
